New Pre-Process
davidanugraha/drug_synergy_pred pull request #15
Opened 2024-03-24 19:06 UTC by martinyang0416

2024-03-24 21:37 UTC, davidanugraha commented on src/preprocess.py
> +rdkit_features =  ['MaxEStateIndex', 'MinEStateIndex', 'MaxAbsEStateIndex', 'MinAbsEStateIndex', 'qed', 'MolWt', 'HeavyAtomMolWt', 'ExactMolWt', 'NumValenceElectrons', 'NumRadicalElectrons', 'FpDensi
Too messy, refactor variable names to top of the file

2024-03-24 21:43 UTC, davidanugraha requested changes

2024-03-24 21:43 UTC, davidanugraha commented on src/preprocess.py
> +               ]
Missing GetChiralTag

2024-03-24 21:43 UTC, davidanugraha commented on src/preprocess.py
> +rdkit_features =  ['MaxEStateIndex', 'MinEStateIndex', 'MaxAbsEStateIndex', 'MinAbsEStateIndex', 'qed', 'MolWt', 'HeavyAtomMolWt', 'ExactMolWt', 'NumValenceElectrons', 'NumRadicalElectrons', 'FpDensi
Too messy, refactor variable names to top of the file

2024-03-24 21:43 UTC, davidanugraha commented on src/preprocess.py
> +rdkit_features =  ['MaxEStateIndex', 'MinEStateIndex', 'MaxAbsEStateIndex', 'MinAbsEStateIndex', 'qed', 'MolWt', 'HeavyAtomMolWt', 'ExactMolWt', 'NumValenceElectrons', 'NumRadicalElectrons', 'FpDensi
Also have you tested this? Are you sure these values are numerically stable. In addition, are 3D Features included in here as well?

2024-03-25 02:48 UTC, derrickkkkk commented on src/preprocess.py
> +               ]
GetChiralTag is not Numerical

2024-03-25 03:44 UTC, davidanugraha commented on src/preprocess.py
> +               ]
Yes, have to make it Categorical as I mentioned

2024-03-28 03:32 UTC, davidanugraha commented on src/preprocess.py
> +ChiralTags = ['CHI_UNSPECIFIED', 'CHI_TETRAHEDRAL_CW', 'CHI_TETRAHEDRAL_CCW', 'CHI_OTHER']
Are you sure these are all the ChiralTags? I remember it's more than this, please refer to documentation of Rdkit please

2024-03-28 03:50 UTC, davidanugraha requested changes
Please see the comments and fix them.

2024-03-28 03:50 UTC, davidanugraha commented on src/preprocess.py
> +ChiralTags = ['CHI_UNSPECIFIED', 'CHI_TETRAHEDRAL_CW', 'CHI_TETRAHEDRAL_CCW', 'CHI_OTHER']
[ChiralType](https://www.rdkit.org/docs/cppapi/classRDKit_1_1Atom.html#a8a82ae947ebbbc48f5ec5128f5c3e724) {
  [CHI_UNSPECIFIED](https://www.rdkit.org/docs/cppapi/classRDKit_1_1Atom.html#a8a82ae947ebbbc48f5ec5128f5c3e724a964d8c1bfb4dd140e8c56538df248139) = 0 , [CHI_TETRAHEDRAL_CW](https://www.rdkit.org/docs/cppapi/classRDKit_1_1Atom.html#a8a82ae947ebbbc48f5ec5128f5c3e724a8c09352c68561c82ac07f27f75911fdd) , [CHI_TETRAHEDRAL_CCW](https://www.rdkit.org/docs/cppapi/classRDKit_1_1Atom.html#a8a82ae947ebbbc48f5ec5128f5c3e724aa95768d8f526ebcd9f01410b73a1e6fd) , [CHI_OTHER](https://www.rdkit.org/docs/cppapi/classRDKit_1_1Atom.html#a8a82ae947ebbbc48f5ec5128f5c3e724a29e23be90b99e1255fe2ddb4be817157) ,
  [CHI_TETRAHEDRAL](https://www.rdkit.org/docs/cppapi/classRDKit_1_1Atom.html#a8a82ae947ebbbc48f5ec5128f5c3e724a6e4dc33ab4e36387e517e7e6cf3ba598) , [CHI_ALLENE](https://www.rdkit.org/docs/cppapi/classRDKit_1_1Atom.html#a8a82ae947ebbbc48f5ec5128f5c3e724a74d2d5b724ce5022c7b7f2bbae28f497) , [CHI_SQUAREPLANAR](https://www.rdkit.org/docs/cppapi/classRDKit_1_1Atom.html#a8a82ae947ebbbc48f5ec5128f5c3e724af64e94d024b146c6147ef561ca228e7e) , [CHI_TRIGONALBIPYRAMIDAL](https://www.rdkit.org/docs/cppapi/classRDKit_1_1Atom.html#a8a82ae947ebbbc48f5ec5128f5c3e724ab3840bb1ccb4b294a85ea327b34d94ea) ,
  [CHI_OCTAHEDRAL](https://www.rdkit.org/docs/cppapi/classRDKit_1_1Atom.html#a8a82ae947ebbbc48f5ec5128f5c3e724a9f32ced132f353561e5dcd81582fe609)
}

2024-03-28 03:50 UTC, davidanugraha commented on src/preprocess.py
> +ChiralTags = ['CHI_UNSPECIFIED', 'CHI_TETRAHEDRAL_CW', 'CHI_TETRAHEDRAL_CCW', 'CHI_OTHER']
Also please fix naming to all capital

2024-03-28 03:50 UTC, davidanugraha commented on src/preprocess.py
> +ChiralTags = ['CHI_UNSPECIFIED', 'CHI_TETRAHEDRAL_CW', 'CHI_TETRAHEDRAL_CCW', 'CHI_OTHER']
Duplicated code?

2024-03-28 03:50 UTC, davidanugraha commented on src/preprocess.py
> +               ] + one_hot_encoding(atom.GetChiralTag(), ChiralTags)
Please use pandas

2024-03-28 03:50 UTC, davidanugraha commented on src/preprocess.py
> +rdkit_features =  ['MaxEStateIndex', 'MinEStateIndex', 'MaxAbsEStateIndex', 'MinAbsEStateIndex', 'qed', 'MolWt', 'HeavyAtomMolWt', 'ExactMolWt', 'NumValenceElectrons', 'NumRadicalElectrons', 'FpDensi
Same, make it capital. Also, I don't see any HOMO, LUMO attributes for 3D, where is it?

2024-03-28 03:50 UTC, davidanugraha commented on src/preprocess.py
> +        #     values_list.append(0)
Commented codes should be cleaned and removed

2024-03-28 03:50 UTC, davidanugraha commented on src/preprocess.py
> +            print(f"Warning: Property '{property_name}' did not return a numerical value.")
Use logging

2024-04-09 20:20 UTC, merged